name: Build
on: [push, workflow_dispatch]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: "Java Virtual Machine"
            testTask: "jvmTest"
    runs-on: ubuntu-latest
    container:
      image: gradle
    name: ${{ matrix.platform.name }}
    steps:

      - name: Checkout Repository
        uses: "actions/checkout@v2"

      - name: Start Gradle Daemon
        run: "gradle prepareKotlinBuildScriptModel"

      - name: Build & Test - Annotations
        run: "gradle kommons-annotations:${{ matrix.platform.testTask }}"

      - name: Build & Test - Assertions
        run: "gradle kommons-assertions:${{ matrix.platform.testTask }}"

      - name: Build & Test - Bill of Materials
        run: "gradle kommons-bom:${{ matrix.platform.testTask }}"

      - name: Build & Test - Encoding
        run: "gradle kommons-encoding:${{ matrix.platform.testTask }}"

      - name: Build & Test - INI Files
        run: "gradle kommons-ini:${{ matrix.platform.testTask }}"

      - name: Build & Test - I/O
        run: "gradle kommons-io:${{ matrix.platform.testTask }}"

      - name: Build & Test - Logging
        run: "gradle kommons-logging:${{ matrix.platform.testTask }}"

      - name: Build & Test - Parser
        run: "gradle kommons-parser:${{ matrix.platform.testTask }}"

      - name: Build & Test - Security
        run: "gradle kommons-security:${{ matrix.platform.testTask }}"

      - name: Build & Test - Utilities
        run: "gradle kommons-utils:${{ matrix.platform.testTask }}"

      - name: Build & Test - UUID
        run: "gradle kommons-uuid:${{ matrix.platform.testTask }}"

      - name: Build & Test - Version
        run: "gradle kommons-version:${{ matrix.platform.testTask }}"
