name: Build
on: [push, workflow_dispatch]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: "Java Virtual Machine"
            testTask: "jvmTest"
    runs-on: ubuntu-latest
    container:
      image: gradle
    name: ${{ matrix.platform.name }}
    steps:

      - name: Checkout Repository
        uses: "actions/checkout@v2"

      - name: Start Gradle Daemon
        run: "gradle prepareKotlinBuildScriptModel"

      - name: Build & Test - Annotations
        run: "gradle commons-annotations:${{ matrix.platform.testTask }}"
        continue-on-error: true

      - name: Build & Test - Assertions
        run: "gradle commons-assertions:${{ matrix.platform.testTask }}"
        continue-on-error: true

      - name: Build & Test - Bill of Materials
        run: "gradle commons-bom:${{ matrix.platform.testTask }}"
        continue-on-error: true

      - name: Build & Test - Encoding
        run: "gradle commons-encoding:${{ matrix.platform.testTask }}"
        continue-on-error: true

      - name: Build & Test - INI Files
        run: "gradle commons-ini:${{ matrix.platform.testTask }}"
        continue-on-error: true

      - name: Build & Test - Logging
        run: "gradle commons-logging:${{ matrix.platform.testTask }}"
        continue-on-error: true

      - name: Build & Test - Parser
        run: "gradle commons-parser:${{ matrix.platform.testTask }}"
        continue-on-error: true

      - name: Build & Test - Security
        run: "gradle commons-security:${{ matrix.platform.testTask }}"
        continue-on-error: true

      - name: Build & Test - Utilities
        run: "gradle commons-utils:${{ matrix.platform.testTask }}"
        continue-on-error: true
