name: Build
on: [push, workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container:
      image: gradle
    steps:
      - name: Checkout Repository
        uses: "actions/checkout@v2"
      - name: Start Gradle Daemon
        run: "gradle init"
      - name: Build
        run: "gradle assemble"
      - name: Test
        run: "gradle test"

