name: "Release"
on:
  release:
    types:
      - released
      - prereleased
  workflow_dispatch:

jobs:

  build:
    name: "Build"
    runs-on: "ubuntu-latest"
    container:
      image: "gradle"
    env:
      PUBLISH_MAVEN_USERNAME: ${{ secrets.PUBLISH_MAVEN_USERNAME }}
      PUBLISH_MAVEN_PASSWORD: ${{ secrets.PUBLISH_MAVEN_PASSWORD }}
    steps:

      - name: "Checkout Repository"
        uses: "actions/checkout@v2"

      - name: "Start Gradle Daemon"
        run: "gradle clean"

      - name: "Compile Project"
        run: "gradle assemble"

      - name: "Build & Test Project"
        run: "gradle build"

      - name: "Publish Project"
        run: "gradle publish"
